//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 gb.rc 使用
//
#define IDC_MYICON                      2
#define IDD_GB_DIALOG                   102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_GB                          107
#define IDI_SMALL                       108
#define IDC_GB                          109
#define IDD_SHURUKUANG                  110
#define IDR_MAINFRAME                   128
#define IDD_DIALOG2                     130
#define IDD_DIALOG_SET_MONEY            131
#define IDD_DIALOG_STORAGE              132
#define IDD_DIALOG_LOGIN                133
#define IDM_LOGIN                       134
#define IDM_STORAGE                     135
#define IDD_DIALOG_CHOOSE_PRODUCT       137
#define IDD_DIALOG_PORT_CONFIG          138
#define IDM_PORT_CONFIG                 139
#define IDB_PNG1                        140
#define IDI_ICON1                       142
#define IDI_ICON2                       143
#define IDR_MENU1                       144
#define IDR_MENU_STORAGE                145
#define IDM_ADMIN_URL                   146
#define IDD_DIALOG_SUPPLIERS_LIST       146
#define IDM_SUPPLIERS_ADD               147
#define IDD_DIALOG_SUPPLIERS_CHOOSE     147
#define IDM_SUPPLIERS_MANAGE            148
#define IDD_DIALOG_SUPPLIERS_ADD        149
#define IDD_DIALOG_SUPPLIERS_EDIT       150
#define IDI_ICON_MAIN                   151
#define IDD_DIALOG_STORAGE_SINGLE       152
#define IDB_BITMAP_SINGLE_NW            157
#define IDB_BITMAP_SINGLE_TARE          158
#define IDB_BITMAP_SINGLE_SAVE          159
#define IDB_BITMAP_SINGLE_PRINT         160
#define IDD_DIALOG1                     161
#define IDD_DIALOG_PLATE_NUMBER         161
#define IDC_COMBO_PRODUCT_CODE          1011
#define IDC_LIST_STORAGE                1012
#define IDC_EDIT_SEARCHKEY              1013
#define IDC_EDIT_ACCOUNT                1014
#define IDC_EDIT_PASSWORD               1015
#define IDC_BUTTON_BT_COM               1018
#define IDC_BUTTON_BC_                  1019
#define IDC_BUTTON_BC_COM               1019
#define IDC_CHECK1                      1020
#define IDC_BUTTON_ST_COM               1022
#define IDC_BUTTON_SC_COM               1023
#define IDC_DO_LOGIN                    1023
#define IDC_BUTTON_SINGLE_TARE          1024
#define IDC_BUTTON_SINGLE_PRINT         1025
#define IDC_BUTTON_SINGLE_SAVE          1026
#define IDC_DATETIMEPICKER2             1027
#define IDC_BUTTON_PAY                  1028
#define IDC_BUTTON_SET_MONEY            1029
#define IDC_BUTTON_ONLINE_SCORE         1030
#define IDC_BUTTON_STORAGE_FAIL         1031
#define IDC_TAB_USER                    1032
#define IDC_BUTTON_OPEN_ADMIN           1033
#define IDC_BUTTON_PORT_CONFIG          1034
#define IDC_BUTTON_SEARCH               1035
#define IDC_BUTTON_SC_COM_ZERO          1036
#define IDC_BUTTON_ADD_NEW_GUEST        1041
#define IDC_TAB_STORAGE                 1042
#define IDC_BUTTON_SET_SURE             1043
#define IDC_BUTTON_SET_CANCLE           1044
#define IDC_EDIT_PRODUCT_NAME           1045
#define IDC_EDIT_SET_MONEY              1046
#define IDC_BUTTON_CHOOSE_CATEGORY      1047
#define IDC_LIST_PRODUCTS               1049
#define IDC_BUTTON_CHOOSE               1050
#define IDC_TAB_PORT_CONFIG             1051
#define IDC_BUTTON_CHOOSE_CANCEL        1051
#define IDC_BUTTON_PORT_CONFIG_SAVE     1052
#define IDC_COMBO_SELECT_TYPE           1054
#define IDC_BUTTON_READ_IC              1055
#define IDC_BUTTON_CHOOSE_SUPPLIERS     1056
#define IDC_BUTTON_SUPPLIERS_WRITE_IC   1062
#define IDC_MFCMENUBUTTON1              1066
#define IDC_LIST_SUPPLIERS_CHOOSE       1068
#define IDC_EDIT_SUPPLIERS_BZ           1069
#define IDC_EDIT_SUPPLIERS_NAME         1070
#define IDC_EDIT_SUPPLIERS_IC           1071
#define IDC_EDIT_SUPPLIERS_CONTACT      1072
#define IDC_EDIT_SUPPLIERS_MOBILE       1073
#define IDC_EDIT_SUPPLIERS_ADDRESS      1074
#define IDC_COMBO_CTYPE                 1076
#define IDC_COMBO_HTYPE                 1077
#define IDC_BUTTON_SUPPLIERS_ADD_SURE   1078
#define IDC_EDIT_SUPPLIERS_LIST_IC      1080
#define IDC_EDIT_SUPPLIERS_LIST_CONTACT 1082
#define IDC_EDIT_SUPPLIERS_LIST_NAME    1083
#define IDC_BUTTON_SUPPLIERS_LIST_SEARCH 1084
#define IDC_BUTTON_SUPPLIERS_LIST_ADD   1085
#define IDC_LIST_SUPPLIERS_LIST         1086
#define IDC_BUTTON_SUPPLIERS_FRISTPAGE  1087
#define IDC_BUTTON_SUPPLIERS_LIST_UP    1088
#define IDC_BUTTON_SUPPLIERS_LIST_DOWN  1089
#define IDC_BUTTON_SUPPLIERS_LASTPAGE   1090
#define IDC_BUTTON_SUPPLIERS_LIST_EDIT  1091
#define IDC_BUTTON_SUPPLIERS_LIST_DEL   1092
#define IDC_STATIC_SUPPLIERS_LIST_PAGES 1093
#define IDC_STATIC_SUPPLIERS_LIST_TOTALS 1094
#define IDC_EDIT_SUPPLIERS_LIST_MOBILE  1095
#define IDC_BUTTON_SUPPLIERS_LIST_SEARCH_ALL 1096
#define IDC_BUTTON_SUPPLIERS_SAVE_SURE  1097
#define IDC_BUTTON_SUPPLIERS_LIST_REFRESH 1098
#define IDC_LIST_STORAGE_SINGLE_LIST    1099
#define IDC_RADIO_SINGLE_IN             1100
#define IDC_RADIO_SINGLE_OUT            1101
#define IDC_EDIT1                       1102
#define IDC_BUTTON1                     1103
#define IDC_EDIT_SINGLE_CONTACT         1104
#define IDC_BUTTON2                     1105
#define IDC_EDIT_SINGLE_GW              1106
#define IDC_EDIT_SINGLE_TARE            1107
#define IDC_EDIT_SINGLE_NW              1108
#define IDC_EDIT_SINGLE_BZ              1109
#define IDC_EDIT_SINGLE_IC              1110
#define IDC_BUTTON3                     1111
#define IDC_BUTTON13                    1111
#define IDC_EDIT8                       1112
#define IDC_BUTTON14                    1112
#define IDC_EDIT_SINGLE_PRODUCT_NAME    1112
#define IDC_BUTTON_CHOOSE_PRODUCT       1113
#define IDC_EDIT_SINGLE_PRICE           1114
#define IDC_EDIT_SEARCH_DATE_FROM       1115
#define IDC_BUTTON17                    1115
#define IDC_EDIT_SEARCH_DATE_TO         1116
#define IDC_BUTTON18                    1116
#define IDC_COMBO_SEARCH_SIZE           1117
#define IDC_BUTTON19                    1117
#define IDC_COMBO_SEARCH_STATUS         1117
#define IDC_BUTTON9                     1118
#define IDC_BUTTON10                    1119
#define IDC_STATIC_KK2                  1120
#define IDC_BUTTON20                    1120
#define IDC_STATIC_SEARCH_BAR_TIME      1121
#define IDC_BUTTON21                    1121
#define IDC_BUTTON_STORAGE_SINGLE_GW    1122
#define IDC_BUTTON22                    1122
#define IDC_BUTTON23                    1123
#define IDC_BUTTON24                    1124
#define IDC_BUTTON25                    1125
#define IDC_BUTTON26                    1126
#define IDC_BUTTON27                    1127
#define IDC_BUTTON28                    1128
#define IDC_BUTTON29                    1129
#define IDC_BUTTON30                    1130
#define IDC_BUTTON31                    1131
#define IDC_BUTTON32                    1132
#define IDC_BUTTON33                    1133
#define IDC_EDIT_PLATE_NUMBER           1134
#define IDC_BUTTON_CHOOSE_PLATE_NUMBER  1135
#define IDC_BUTTON34                    1136
#define IDC_BUTTON35                    1137
#define IDC_BUTTON36                    1138
#define IDC_DATETIMEPICKER_SINGLE_TO    1138
#define IDC_BUTTON37                    1139
#define IDC_DATETIMEPICKER_SINGLE_FROM  1139
#define IDC_BUTTON38                    1140
#define IDC_BUTTON39                    1141
#define IDC_BUTTON40                    1142
#define IDC_BUTTON41                    1143
#define IDC_BUTTON42                    1144
#define IDC_BUTTON43                    1145
#define IDC_BUTTON44                    1146
#define IDC_BUTTON45                    1147
#define IDC_BUTTON46                    1148
#define IDC_BUTTON47                    1149
#define IDC_BUTTON48                    1150
#define IDC_BUTTON49                    1151
#define IDC_BUTTON50                    1152
#define IDC_BUTTON51                    1153
#define IDC_BUTTON52                    1154
#define IDC_BUTTON53                    1155
#define IDC_BUTTON54                    1156
#define IDC_BUTTON55                    1157
#define IDC_BUTTON56                    1158
#define IDC_BUTTON57                    1159
#define IDC_BUTTON58                    1160
#define IDC_BUTTON59                    1161
#define IDC_BUTTON60                    1169
#define IDC_BUTTON61                    1170
#define IDC_BUTTON_PLATE_1              1171
#define IDC_BUTTON_PLATE_2              1172
#define IDC_BUTTON_PLATE_3              1173
#define IDC_BUTTON_PLATE_4              1174
#define IDC_BUTTON_PLATE_5              1175
#define IDC_BUTTON_PLATE_6              1176
#define IDC_BUTTON_PLATE_7              1177
#define IDC_BUTTON_PLATE_8              1178
#define IDC_BUTTON_PLATE_9              1179
#define IDC_BUTTON_PLATE_10             1180
#define IDC_BUTTON_PLATE_11             1181
#define IDC_BUTTON_PLATE_12             1182
#define IDC_BUTTON_PLATE_13             1183
#define IDC_BUTTON_PLATE_14             1184
#define IDC_BUTTON_PLATE_15             1185
#define IDC_BUTTON_PLATE_16             1186
#define IDC_BUTTON_PLATE_17             1187
#define IDC_BUTTON_PLATE_18             1188
#define IDC_BUTTON_PLATE_19             1189
#define IDC_BUTTON_PLATE_20             1190
#define IDC_BUTTON_PLATE_21             1191
#define IDC_BUTTON_PLATE_22             1192
#define IDC_BUTTON_PLATE_23             1193
#define IDC_BUTTON_PLATE_24             1194
#define IDC_BUTTON_PLATE_25             1195
#define IDC_BUTTON_PLATE_26             1196
#define IDC_BUTTON_PLATE_27             1197
#define IDC_BUTTON_PLATE_28             1198
#define IDC_BUTTON_PLATE_29             1199
#define IDC_BUTTON_PLATE_30             1200
#define IDC_BUTTON_PLATE_31             1201
#define IDC_BUTTON_PLATE_J              1202
#define IDC_BUTTON_PLATE_S0             1210
#define IDC_BUTTON_PLATE_S1             1211
#define IDC_BUTTON_PLATE_S2             1212
#define IDC_BUTTON_PLATE_S3             1213
#define IDC_BUTTON_PLATE_S4             1214
#define IDC_BUTTON_PLATE_S5             1215
#define IDC_BUTTON_PLATE_S6             1216
#define IDC_BUTTON_PLATE_S7             1217
#define IDC_BUTTON_PLATE_S8             1218
#define IDC_BUTTON_PLATE_S9             1219
#define IDC_BUTTON_PLATE_ZA             1220
#define IDC_BUTTON_PLATE_ZB             1221
#define IDC_BUTTON_PLATE_ZC             1222
#define IDC_BUTTON_PLATE_ZD             1223
#define IDC_BUTTON_PLATE_ZE             1224
#define IDC_BUTTON_PLATE_ZF             1225
#define IDC_BUTTON_PLATE_ZG             1226
#define IDC_BUTTON_PLATE_ZH             1227
#define IDC_BUTTON_PLATE_ZI             1228
#define IDC_BUTTON_PLATE_ZJ             1229
#define IDC_BUTTON_PLATE_ZK             1230
#define IDC_BUTTON_PLATE_ZL             1231
#define IDC_BUTTON_PLATE_ZM             1232
#define IDC_BUTTON_PLATE_ZN             1233
#define IDC_BUTTON_PLATE_ZO             1234
#define IDC_BUTTON_PLATE_ZP             1235
#define IDC_BUTTON_PLATE_ZQ             1236
#define IDC_BUTTON_PLATE_ZR             1237
#define IDC_BUTTON_PLATE_ZS             1238
#define IDC_BUTTON_PLATE_ZT             1239
#define IDC_BUTTON_PLATE_ZU             1240
#define IDC_BUTTON_PLATE_ZV             1241
#define IDC_BUTTON_PLATE_ZW             1242
#define IDC_BUTTON_PLATE_ZX             1243
#define IDC_BUTTON_PLATE_ZY             1244
#define IDC_BUTTON_PLATE_ZZ             1245
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
